# Generated by Django 5.1.6 on 2026-02-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_songpacket_version_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='song',
            new_name='songs_song_title_2cbace_idx',
            old_name='songs_song_title_067546_idx',
        ),
        migrations.RenameIndex(
            model_name='song',
            new_name='songs_song_languag_1e13b6_idx',
            old_name='songs_song_languag_4da08a_idx',
        ),
        migrations.RenameIndex(
            model_name='songpacket',
            new_name='songs_songp_session_440ef0_idx',
            old_name='songs_songp_session_3705d4_idx',
        ),
        migrations.RenameIndex(
            model_name='songpacketeditevent',
            new_name='songs_songp_packet__18ce95_idx',
            old_name='songs_songp_packet__6360d8_idx',
        ),
        migrations.RenameIndex(
            model_name='songpacketversion',
            new_name='songs_songp_packet__dde15d_idx',
            old_name='songs_songp_packet__81f050_idx',
        ),
    ]
