from django.urls import path

from .views import (
    ApiRootView,
    MatchSongsView,
    PacketGenerateView,
    PacketOptimizeOrderView,
    PacketPreviewView,
    SongPacketActivateVersionView,
    SongPacketDetailView,
    SongPacketHistoryView,
    SongPacketListCreateView,
    SongPacketOpenLatestView,
    SongPacketSaveVersionView,
    SongPacketStateView,
    SongPacketVersionGenerateView,
    SongPacketVersionListView,
    SongbaseSourceSampleInspectView,
    SongbaseSourceSampleView,
    SongbaseSyncView,
    SongVersionListView,
)

urlpatterns = [
    path('', ApiRootView.as_view(), name='api-root'),
    path('songs/match', MatchSongsView.as_view(), name='songs-match'),
    path('songs/<int:song_id>/versions', SongVersionListView.as_view(), name='song-versions'),
    path('songs/sync', SongbaseSyncView.as_view(), name='songs-sync'),
    path('songs/source-sample', SongbaseSourceSampleView.as_view(), name='songs-source-sample'),
    path('songs/source-sample/inspect', SongbaseSourceSampleInspectView.as_view(), name='songs-source-sample-inspect'),
    path('packet/preview', PacketPreviewView.as_view(), name='packet-preview'),
    path('packet/generate', PacketGenerateView.as_view(), name='packet-generate'),
    path('packet/optimize-order', PacketOptimizeOrderView.as_view(), name='packet-optimize-order'),
    path('song-packets', SongPacketListCreateView.as_view(), name='song-packets'),
    path('song-packets/<int:packet_id>', SongPacketDetailView.as_view(), name='song-packet-detail'),
    path('song-packets/<int:packet_id>/open-latest', SongPacketOpenLatestView.as_view(), name='song-packet-open-latest'),
    path('song-packets/<int:packet_id>/state', SongPacketStateView.as_view(), name='song-packet-state'),
    path('song-packets/<int:packet_id>/save-version', SongPacketSaveVersionView.as_view(), name='song-packet-save-version'),
    path('song-packets/<int:packet_id>/versions', SongPacketVersionListView.as_view(), name='song-packet-versions'),
    path('song-packets/<int:packet_id>/history', SongPacketHistoryView.as_view(), name='song-packet-history'),
    path('song-packets/<int:packet_id>/activate-version', SongPacketActivateVersionView.as_view(), name='song-packet-activate-version'),
    path('song-packets/<int:packet_id>/versions/<int:version_id>/generate', SongPacketVersionGenerateView.as_view(), name='song-packet-version-generate'),
]
